const HOBBIES = [
  {
    id: "milo",
    title: "Walking Milo",
    emoji: "🐾",
    emote: "✨🐶💕",
    sound: "sparkle",
    image: "assets/hobbies/hobby-milo.png",
    caption: "Morning walks with my tiny white fluffball, Milo.",
    animation: "bounce",
  },
  {
    id: "roblox",
    title: "Roblox",
    emoji: "🎮",
    emote: "💗🕹️✨",
    sound: "pop",
    image: "assets/hobbies/hobby-roblox.png",
    caption: "Building worlds and vibing with friends online.",
    animation: "pulse",
  },
  {
    id: "workout",
    title: "Working Out",
    emoji: "💪",
    emote: "🔥💪✨",
    sound: "power",
    image: "assets/hobbies/hobby-workout.png",
    caption: "Gym sessions to stay strong and energized.",
    animation: "shake",
  },
  {
    id: "makeup",
    title: "Makeup",
    emoji: "💄",
    emote: "💄✨🎀",
    sound: "chime",
    image: "assets/hobbies/hobby-makeup.png",
    caption: "Glam nights and soft everyday looks.",
    animation: "sparkle",
  },
  {
    id: "shopping",
    title: "Shopping",
    emoji: "🛍️",
    emote: "🛍️💕✨",
    sound: "giggle",
    image: "assets/hobbies/hobby-shopping.png",
    caption: "Mall days and cute fits with my girls.",
    animation: "sway",
  },
  {
    id: "matcha",
    title: "Matcha",
    emoji: "🍵",
    emote: "🍵💚✨",
    sound: "sip",
    image: "assets/hobbies/hobby-matcha.png",
    caption: "Iced matcha runs are my love language.",
    animation: "float",
  },
  {
    id: "travel",
    title: "Traveling",
    emoji: "✈️",
    emote: "✈️🌸💫",
    sound: "whoosh",
    image: "assets/hobbies/hobby-travel.png",
    caption: "New cities, new views, new memories.",
    animation: "drift",
  },
];

const EMOTE_SOUNDS = {
  sparkle: { freq: 880, type: "sine", duration: 0.18, emoji: "✨" },
  pop: { freq: 520, type: "triangle", duration: 0.12, emoji: "💗" },
  power: { freq: 220, type: "square", duration: 0.08, emoji: "💪" },
  chime: { freq: 660, type: "sine", duration: 0.22, emoji: "🎀" },
  giggle: { freq: 740, type: "sine", duration: 0.15, emoji: "😊" },
  sip: { freq: 400, type: "sine", duration: 0.2, emoji: "🍵" },
  whoosh: { freq: 300, type: "sawtooth", duration: 0.14, emoji: "✈️" },
  heart: { freq: 620, type: "sine", duration: 0.16, emoji: "💕" },
  star: { freq: 980, type: "sine", duration: 0.14, emoji: "⭐" },
  bow: { freq: 700, type: "triangle", duration: 0.17, emoji: "🎀" },
};
